services:
  db:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_DB: db_pogrebnyuk
      POSTGRES_USER: username
      POSTGRES_PASSWORD: Qwerty123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django_proj:
    build: .
    command: python base/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/base
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=db_pogrebnyuk
      - DB_USER=username
      - DB_PASSWORD=Qwerty123
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: