services:
  db:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_DB: db_pogrebnyuk
      POSTGRES_USER: username
      POSTGRES_PASSWORD: Qwerty123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_proj:
    container_name: django_proj
    build: .
    volumes:
      - .:/base
      - media_volume:/media

    # ports:
    #   - "8000:8000"

    depends_on:
      - db
    
    env_file:
      - .env

    environment:
      - DJANGO_SETTINGS_MODULE=base.settings
      - DEBUG=1
      - DB_NAME=db_pogrebnyuk
      - DB_USER=username
      - DB_PASSWORD=Qwerty123
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
  media_volume: