services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: db_pogrebnyuk
      POSTGRES_USER: username
      POSTGRES_PASSWORD: Qwerty123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_proj:
    build: .
    volumes:
      - .:/base
      - media_volume:/media

    ports:
      - "8000:8000"

    depends_on:
      - db
    
    env_file:
      - .env

volumes:
  postgres_data:
  media_volume: